{
    "openapi": "3.0.1",
    "info": {
        "title": "Inventory Management",
        "description": "Maintaining up-to-date inventory for your items on Walmart.com ensures a great experience for your customers and greater sales opportunities for you.",
        "version": "0.7.0"
    },
    "servers": [
        {
            "url": "https:\/\/marketplace.walmartapis.com",
            "description": "Production URL"
        },
        {
            "url": "https:\/\/sandbox.walmartapis.com",
            "description": "Sandbox URL"
        }
    ],
    "security": [
        {
            "basicScheme": []
        }
    ],
    "paths": {
        "\/v3\/inventory": {
            "get": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Get Inventory",
                "description": "You can use this API to get the inventory for a given item.",
                "operationId": "getInventory",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "query",
                        "description": "A seller-provided Product ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/Inventory",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "sku-e2e-0723x",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 8596
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "basic": [],
                        "accessToken": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Update inventory",
                "description": "Updates the inventory for a given item.",
                "operationId": "updateInventoryForAnItem",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "query",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, identifying each item.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "File fields",
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/Inventory"
                            },
                            "example": {
                                "sku": "sku-e2e-0723x",
                                "quantity": {
                                    "unit": "EACH",
                                    "amount": 8596
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/Inventory",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "sku-e2e-0723x",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 8598
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "basic": [],
                        "accessToken": []
                    }
                ]
            }
        },
        "\/v3\/feeds": {
            "post": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Update bulk inventory",
                "description": "Updates inventory for items in bulk. Refer to the throttling limits before uploading the Feed files",
                "operationId": "updateBulkInventory",
                "parameters": [
                    {
                        "name": "feedType",
                        "in": "query",
                        "description": "Includes details of each entity in the feed. Do not set this parameter to true.",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "inventory"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart\/form-data": {
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "description": "Feed file to upload",
                                        "format": "binary"
                                    }
                                }
                            },
                            "examples": {
                                "json1": {
                                    "value": {
                                        "InventoryHeader": {
                                            "version": "1.4"
                                        },
                                        "Inventory": [
                                            {
                                                "sku": "sku-e2e-0561x",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "amount": "20"
                                                }
                                            },
                                            {
                                                "sku": "hnbspec1007",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "amount": "30"
                                                }
                                            },
                                            {
                                                "sku": "sku-e2e-0723x",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "amount": "30"
                                                }
                                            }
                                        ]
                                    }
                                },
                                "xml1": {
                                    "value": "<InventoryFeed xmlns=\"http:\/\/walmart.com\/\">\n  <InventoryHeader>\n    <version>1.4<\/version>\n  <\/InventoryHeader>\n  <inventory>\n    <sku>sku-e2e-0561x<\/sku>\n    <quantity>\n      <unit>EACH<\/unit>\n      <amount>10<\/amount>\n    <\/quantity>\n  <\/inventory>\n  <inventory>\n    <sku>hnbspec1007<\/sku>\n    <quantity>\n      <unit>EACH<\/unit>\n      <amount>20<\/amount>\n    <\/quantity>\n  <\/inventory>\n<\/InventoryFeed>"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/FeedId",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "feedId": "3B6F0372F68949A0AB2DD89CE0726FCB@AQkBAQA"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "basic": [],
                        "accessToken": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "Inventory": {
                "required": [
                    "quantity",
                    "sku"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "A seller-provided Product ID"
                    },
                    "quantity": {
                        "$ref": "#\/components\/schemas\/Quantity"
                    }
                }
            },
            "Quantity": {
                "required": [
                    "amount",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "The unit of measurement. Example: 'EACH'",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "The number available in the inventory"
                    }
                },
                "description": "Information about the quantity in inventory"
            },
            "FeedId": {
                "type": "object",
                "properties": {
                    "feedId": {
                        "type": "string",
                        "description": "A unique ID, returned from the Bulk Upload API, used for tracking the feed file"
                    },
                    "additionalAttributes": {
                        "type": "object",
                        "nullable": true
                    },
                    "errors": {
                        "type": "object",
                        "nullable": true
                    }
                }
            }
        },
        "parameters": {
            "authorization": {
                "name": "Authorization",
                "in": "header",
                "description": "Basic authorization header. Base 64 encodes the Client ID and Client Secret retrieved in step two of the integration steps.",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Basic YzcyOTFjNmItNzI5MC00...."
            },
            "accessToken": {
                "name": "WM_SEC.ACCESS_TOKEN",
                "in": "header",
                "description": "The access token retrieved in the Token API call",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM....."
            },
            "channelType": {
                "name": "WM_CONSUMER.CHANNEL.TYPE",
                "in": "header",
                "description": "A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding",
                "required": false,
                "schema": {
                    "type": "string"
                }
            },
            "correlationId": {
                "name": "WM_QOS.CORRELATION_ID",
                "in": "header",
                "description": "A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "b3261d2d-028a-4ef7-8602-633c23200af6"
            },
            "svcName": {
                "name": "WM_SVC.NAME",
                "in": "header",
                "description": "Walmart Service Name",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Walmart Service Name"
            },
            "accept": {
                "name": "Accept",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            },
            "content-type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            }
        },
        "securitySchemes": {
            "accessToken": {
                "type": "http",
                "scheme": "bearer",
                "description": "Header authentication with a Walmart access token, which is automatically generated using your Client ID and Client Secret. The token is valid for 15 minutes, and will be passed in the WM_SEC.ACCESS_TOKEN header"
            },
            "basic": {
                "type": "http",
                "scheme": "basic",
                "description": "Basic authentication with a Walmart Client ID and Client Secret"
            }
        }
    }
}