{
    "openapi": "3.0.1",
    "info": {
        "title": "Inventory Management",
        "description": "Maintaining up-to-date inventory for your items on Walmart.com ensures a great experience for your customers and greater sales opportunities for you.",
        "version": "0.7.0"
    },
    "servers": [
        {
            "url": "https:\/\/marketplace.walmartapis.com",
            "description": "Production URL"
        },
        {
            "url": "https:\/\/sandbox.walmartapis.com",
            "description": "Sandbox URL"
        }
    ],
    "security": [
        {
            "basicScheme": []
        }
    ],
    "paths": {
        "\/v3\/inventory": {
            "get": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Inventory",
                "description": "You can use this API to get the inventory for a given item.",
                "operationId": "getInventory",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "query",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item. This will be used by the seller in the XSD file to refer to each item. Special characters in the sku needing encoding are: ':', '\/', '?', '#', '[', ']', '@', '!', '$', '&', \"'\", '(', ')', '*', '+', ',', ';', '=', \u2018 \u2019, '{', '}' as well as '%' itself if it's a part of sku. Make sure to encode space with %20. Other characters don't need to be encoded.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "The shipNode for which the inventory is requested",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/Inventory",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "97964_KFTest",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 10
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "accessToken": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Update inventory",
                "description": "Updates the inventory for a given item.",
                "operationId": "updateInventoryForAnItem",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "query",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item. This will be used by the seller in the XSD file to refer to each item. Special characters in the sku needing encoding are: ':', '\/', '?', '#', '[', ']', '@', '!', '$', '&', \"'\", '(', ')', '*', '+', ',', ';', '=', \u2018 \u2019, '{', '}' as well as '%' itself if it's a part of sku. Make sure to encode space with %20. Other characters don't need to be encoded.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "The shipNode for which the inventory is to be updated.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "File fields",
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/Inventory"
                            },
                            "example": {
                                "sku": "97964_KFTest",
                                "quantity": {
                                    "unit": "EACH",
                                    "amount": 10
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/Inventory",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "97964_KFTest",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 10
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "accessToken": []
                    }
                ]
            }
        },
        "\/v3\/inventories\/{sku}": {
            "get": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Single Item Inventory by Ship Node",
                "description": "This API will retrieve the inventory count for an item across all ship nodes or one specific ship node. You can specify the ship node for which you want to fetch the inventory",
                "operationId": "getMultiNodeInventoryForSkuAndAllShipnodes",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "path",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item. This will be used by the seller in the XSD file to refer to each item. Special characters in the sku needing encoding are: ':', '\/', '?', '#', '[', ']', '@', '!', '$', '&', \"'\", '(', ')', '*', '+', ',', ';', '=', \u2018 \u2019 as well as '%' itself if it's a part of sku. Make sure to encode space with %20. Other characters don't need to be encoded.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "ShipNode Id of the ship node for which the inventory is requested",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/MultiNodeInventoryUpdateResponseDTO",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "AR-CTIX-0092",
                                    "nodes": [
                                        {
                                            "shipNode": "100009",
                                            "inputQty": {
                                                "unit": "EACH",
                                                "amount": 5
                                            },
                                            "availToSellQty": {
                                                "unit": "EACH",
                                                "amount": 3
                                            },
                                            "reservedQty": {
                                                "unit": "EACH",
                                                "amount": 2
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "accessToken": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Update Item Inventory per Ship Node",
                "description": "This API will update the inventory for an item across one or more fulfillment centers, known as ship nodes.",
                "operationId": "updateMultiNodeInventory",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "path",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item. This will be used by the seller in the XSD file to refer to each item. Special characters in the sku needing encoding are: ':', '\/', '?', '#', '[', ']', '@', '!', '$', '&', \"'\", '(', ')', '*', '+', ',', ';', '=', \u2018 \u2019 as well as '%' itself if it's a part of sku. Make sure to encode space with %20. Other characters don't need to be encoded.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "Request fields",
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/MultiNodeInventoryUpdateRequestDTO"
                            },
                            "example": {
                                "inventories": {
                                    "nodes": [
                                        {
                                            "shipNode": "1000005050",
                                            "inputQty": {
                                                "unit": "EACH",
                                                "amount": 88
                                            }
                                        },
                                        {
                                            "shipNode": "79897837271126017",
                                            "inputQty": {
                                                "unit": "EACH",
                                                "amount": 55
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/MultiNodeInventoryUpdateResponseDTO",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "00757642886669_test_01",
                                    "nodes": [
                                        {
                                            "shipNode": "1000005050",
                                            "status": "Success"
                                        },
                                        {
                                            "shipNode": "79897837271126017",
                                            "status": "Success"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "accessToken": []
                    }
                ]
            }
        },
        "\/v3\/feeds": {
            "post": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Bulk Item Inventory Update",
                "description": "Updates inventory for items in bulk. \nSeller Can either use feed type \"inventory\" or \"MP_INVENTORY\" \n* Inventory spec 1.4 feed type: inventory \n* Inventory spec 1.5 feed type: MP_INVENTORY \n\nPlease Note: Multi Node Inventory Update Feed (feedType=MP_INVENTORY) only supports JSON Request and Responses. Refer to \"MultiNode_Bulk_Inventory_Update_Request.json\" for the corresponding request sample \n \nRefer to the <a href=\"https:\/\/developer.walmart.com\/doc\/us\/us-mp\/us-mp-inventory\/\">guide section<\/a> for more detailed guide around each of the feed types \n\n Refer to the throttling limits before uploading the Feed Files.",
                "operationId": "updateBulkInventory",
                "parameters": [
                    {
                        "name": "feedType",
                        "in": "query",
                        "description": "The feed Type",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "inventory",
                                "MP_INVENTORY"
                            ]
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "The shipNode for which the inventory is to be updated. Not required in case of Multi Node Inventory Update Feed (feedType=MP_INVENTORY)",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart\/form-data": {
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "description": "Feed file to upload",
                                        "format": "binary"
                                    }
                                }
                            },
                            "examples": {
                                "json1": {
                                    "value": {
                                        "InventoryHeader": {
                                            "version": "1.4"
                                        },
                                        "Inventory": [
                                            {
                                                "sku": "test1",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "amount": 10
                                                }
                                            },
                                            {
                                                "sku": "894728",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "amount": 20
                                                }
                                            }
                                        ]
                                    }
                                },
                                "MultiNode_Bulk_Inventory_Update_Request": {
                                    "value": {
                                        "inventoryHeader": {
                                            "version": "1.5"
                                        },
                                        "inventory": [
                                            {
                                                "sku": "190086893939",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 100
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "685387364107_SS4_01",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 21
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "5700521553133_toolsnonwfs_2",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 13
                                                        }
                                                    },
                                                    {
                                                        "shipNode": "1000000352",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 12
                                                        }
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                },
                                "xml1": {
                                    "value": "<InventoryFeed xmlns=\"http:\/\/walmart.com\/\">\n    <InventoryHeader>\n        <version>1.5<\/version>\n    <\/InventoryHeader>\n    <inventory>\n        <sku>test1<\/sku>\n        <quantity>\n            <unit>EACH<\/unit>\n            <amount>10<\/amount>\n        <\/quantity>\n    <\/inventory>\n    <inventory>\n        <sku>894728<\/sku>\n        <quantity>\n            <unit>EACH<\/unit>\n            <amount>20<\/amount>\n        <\/quantity>\n    <\/inventory>\n<\/InventoryFeed>\n"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/FeedId",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "feedId": "FFE538D9B25A4000AD2A067ACEDCF4C4@AUoBAQA"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "accessToken": []
                    }
                ]
            }
        },
        "\/v3\/inventories": {
            "get": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Multiple Item Inventory for All Ship Nodes",
                "description": "This API will retrieve the inventory count for all of a seller's items across all ship nodes by item to ship node mapping. Inventory can be zero or non-zero. Please note that NextCursor value changes and it needs to be passed on from the previous call to next call.",
                "operationId": "getMultiNodeInventoryForAllSkuAndAllShipNodes",
                "parameters": [
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "The number of items returned. Cannot be more than 50.",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "default": "10"
                        }
                    },
                    {
                        "name": "nextCursor",
                        "in": "query",
                        "description": "String returned from initial API call to indicate pagination. Specify nextCursor value to retrieve the next 50 items.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/MultiNodeInventoryFetchResponseDTO",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "meta": {
                                        "totalCount": 123,
                                        "nextCursor": "NTVmZjIxOWEtZjRkMy00MGIwLThkOGYtYzFkNzI1NGZlYmQxIDEw"
                                    },
                                    "elements": {
                                        "inventories": [
                                            {
                                                "sku": "AI-IGH4-5509",
                                                "nodes": [
                                                    {
                                                        "shipNode": "361451354333223041",
                                                        "inputQty": {
                                                            "unit": "EACH",
                                                            "amount": 93
                                                        },
                                                        "availToSellQty": {
                                                            "unit": "EACH",
                                                            "amount": 93
                                                        },
                                                        "reservedQty": {
                                                            "unit": "EACH",
                                                            "amount": 0
                                                        }
                                                    },
                                                    {
                                                        "shipNode": "100009",
                                                        "inputQty": {
                                                            "unit": "EACH",
                                                            "amount": 436
                                                        },
                                                        "availToSellQty": {
                                                            "unit": "EACH",
                                                            "amount": 433
                                                        },
                                                        "reservedQty": {
                                                            "unit": "EACH",
                                                            "amount": 3
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "06397309545443",
                                                "nodes": [
                                                    {
                                                        "shipNode": "100009",
                                                        "inputQty": {
                                                            "unit": "EACH",
                                                            "amount": 5
                                                        },
                                                        "availToSellQty": {
                                                            "unit": "EACH",
                                                            "amount": 0
                                                        },
                                                        "reservedQty": {
                                                            "unit": "EACH",
                                                            "amount": 5
                                                        }
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "accessToken": []
                    }
                ]
            }
        },
        "\/v3\/fulfillment\/inventory": {
            "get": {
                "tags": [
                    "Inventory"
                ],
                "summary": "WFS Inventory",
                "description": "You can use this API to get the current Available to Sell inventory quantities for all WFS items in your catalog. You can also query specific SKUs or filter to only items updated after a specific date in order to reduce the response size.",
                "operationId": "getWFSInventory",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "query",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item. This will be used by the seller in the XSD file to refer to each item. Special characters in the sku needing encoding are: ':', '\/', '?', '#', '[', ']', '@', '!', '$', '&', \"'\", '(', ')', '*', '+', ',', ';', '=', \u2018 \u2019 as well as '%' itself if it's a part of sku. Make sure to encode space with %20. Other characters don't need to be encoded.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "fromModifiedDate",
                        "in": "query",
                        "description": "last inventory modified date - starting range.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "toModifiedDate",
                        "in": "query",
                        "description": "last inventory modified date - starting range.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "Number of Sku to be returned. Cannot be larger than 300.",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "default": "10"
                        }
                    },
                    {
                        "name": "offset",
                        "in": "query",
                        "description": "Offset is the number of records you wish to skip before selecting records.",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "default": "0"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/WfsInventoryDTO",
                                    "x-expose-headers": true
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "accessToken": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "Inventory": {
                "required": [
                    "quantity",
                    "sku"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "A seller-provided Product ID. Response will have decoded value."
                    },
                    "quantity": {
                        "$ref": "#\/components\/schemas\/InputQty"
                    }
                },
                "xml": {
                    "name": "inventory"
                }
            },
            "SupplyQuantity": {
                "required": [
                    "amount",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "The unit of measurement. Example: 'EACH'",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Inventory Count"
                    }
                },
                "description": "Quantity that has been ordered by the customers but not yet shipped"
            },
            "Cause": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "field": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "xml": {
                    "name": "Cause"
                }
            },
            "Error": {
                "required": [
                    "code"
                ],
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "field": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "info": {
                        "type": "string"
                    },
                    "severity": {
                        "type": "string",
                        "enum": [
                            "INFO",
                            "WARN",
                            "ERROR"
                        ]
                    },
                    "category": {
                        "type": "string",
                        "enum": [
                            "APPLICATION",
                            "SYSTEM",
                            "REQUEST",
                            "DATA"
                        ]
                    },
                    "causes": {
                        "type": "array",
                        "xml": {
                            "wrapped": true
                        },
                        "items": {
                            "$ref": "#\/components\/schemas\/Cause"
                        }
                    },
                    "errorIdentifiers": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "object"
                        }
                    }
                },
                "xml": {
                    "name": "Error"
                }
            },
            "MultiNodeInventoryUpdateResponseDTO": {
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item."
                    },
                    "nodes": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/UpdateInventoriesResponseNodeDTO"
                        }
                    }
                }
            },
            "UpdateInventoriesResponseNodeDTO": {
                "type": "object",
                "properties": {
                    "shipNode": {
                        "type": "string",
                        "description": "ShipNode Id of the ship node for which the inventory is requested"
                    },
                    "status": {
                        "type": "string",
                        "description": "Node Update status. Example: 'Success'"
                    },
                    "errors": {
                        "type": "array",
                        "description": "Node Update Error description.",
                        "items": {
                            "$ref": "#\/components\/schemas\/Error"
                        }
                    }
                }
            },
            "MultiNodeInventoryUpdateRequestDTO": {
                "required": [
                    "inventories"
                ],
                "type": "object",
                "properties": {
                    "inventories": {
                        "$ref": "#\/components\/schemas\/UpdateInventoriesRequestDTO"
                    }
                }
            },
            "UpdateInventoriesRequestDTO": {
                "required": [
                    "nodes"
                ],
                "type": "object",
                "properties": {
                    "nodes": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/UpdateInventoriesRequestNodeDTO"
                        }
                    }
                }
            },
            "UpdateInventoriesRequestNodeDTO": {
                "required": [
                    "inputQty",
                    "shipNode"
                ],
                "type": "object",
                "properties": {
                    "shipNode": {
                        "type": "string",
                        "description": "ShipNode Id of the ship node for which the inventory is requested"
                    },
                    "inputQty": {
                        "$ref": "#\/components\/schemas\/InputQty"
                    }
                }
            },
            "FeedId": {
                "type": "object",
                "properties": {
                    "feedId": {
                        "type": "string",
                        "description": "A unique ID, returned from the Bulk Upload API, used for tracking the feed file"
                    },
                    "additionalAttributes": {
                        "type": "object",
                        "nullable": true
                    },
                    "errors": {
                        "type": "object",
                        "nullable": true
                    }
                }
            },
            "Elements": {
                "type": "object",
                "properties": {
                    "inventories": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/GetAllInventoriesDTO"
                        }
                    }
                }
            },
            "GetAllInventoriesDTO": {
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item."
                    },
                    "nodes": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/GetAllInventoriesNodeDTO"
                        }
                    }
                }
            },
            "GetAllInventoriesNodeDTO": {
                "type": "object",
                "properties": {
                    "shipNode": {
                        "type": "string",
                        "description": "ShipNode Id of the ship node for which the inventory is requested"
                    },
                    "inputQty": {
                        "$ref": "#\/components\/schemas\/InputQty"
                    },
                    "availToSellQty": {
                        "$ref": "#\/components\/schemas\/AvailToSellQty"
                    },
                    "reservedQty": {
                        "$ref": "#\/components\/schemas\/ReservedQty"
                    }
                }
            },
            "Meta": {
                "type": "object",
                "properties": {
                    "totalCount": {
                        "type": "number",
                        "description": "Total number of Skus of the Seller. Example: '235'"
                    },
                    "nextCursor": {
                        "type": "string",
                        "description": "Used for pagination to fetch the next set of items."
                    }
                },
                "xml": {
                    "name": "meta"
                }
            },
            "MultiNodeInventoryFetchResponseDTO": {
                "type": "object",
                "properties": {
                    "meta": {
                        "$ref": "#\/components\/schemas\/Meta"
                    },
                    "elements": {
                        "$ref": "#\/components\/schemas\/MultiNodeInventoryUpdateRequestDTO"
                    }
                }
            },
            "InventoriesDTO": {
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item."
                    },
                    "nodes": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/NodeDTO"
                        }
                    }
                }
            },
            "NodeDTO": {
                "type": "object",
                "properties": {
                    "shipNode": {
                        "type": "string",
                        "description": "ShipNode Id of the ship node for which the inventory is requested"
                    },
                    "inputQty": {
                        "$ref": "#\/components\/schemas\/InputQty"
                    },
                    "availToSellQty": {
                        "$ref": "#\/components\/schemas\/AvailToSellQty"
                    },
                    "errors": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/Error"
                        }
                    },
                    "reservedQty": {
                        "$ref": "#\/components\/schemas\/ReservedQty"
                    }
                }
            },
            "Headers": {
                "type": "object",
                "properties": {
                    "totalCount": {
                        "type": "integer",
                        "description": "Total number of results for query.",
                        "format": "int32"
                    },
                    "limit": {
                        "type": "integer",
                        "description": "Information about the quantity in inventory",
                        "format": "int32"
                    },
                    "offset": {
                        "type": "integer",
                        "description": "Offset is the number of records you wish to skip before selecting results.",
                        "format": "int32"
                    }
                }
            },
            "InventoryWFS": {
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item."
                    },
                    "shipNodes": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/ShipNodes"
                        }
                    }
                }
            },
            "Payload": {
                "type": "object",
                "properties": {
                    "inventory": {
                        "type": "array",
                        "items": {
                            "$ref": "#\/components\/schemas\/InventoryWFS"
                        }
                    }
                }
            },
            "ShipNodes": {
                "type": "object",
                "properties": {
                    "modifiedDate": {
                        "type": "string",
                        "description": "Last changes date for the item."
                    },
                    "availToSellQty": {
                        "type": "integer",
                        "description": "The available quantity is the quantity of an item that is available to be allocated to orders.",
                        "format": "int32"
                    },
                    "onHandQty": {
                        "type": "integer",
                        "description": "The on-hand balance is the quantity of active inventory stored at the warehouse.Active inventory is defined as the usable amount of an item that is in the warehouse.Inventory is active if it is not damaged, expired or being inspected.",
                        "format": "int32"
                    },
                    "shipNodeType": {
                        "type": "string",
                        "description": "Identifies fulfillment aspect of invetory. Walmart, seller or 3PL fulfilled. Possible value is 'WFSFulfilled'. In later phase we will also add seller fulfilled inventory."
                    }
                }
            },
            "WfsInventoryDTO": {
                "type": "object",
                "properties": {
                    "headers": {
                        "$ref": "#\/components\/schemas\/Headers"
                    },
                    "payload": {
                        "$ref": "#\/components\/schemas\/Payload"
                    }
                }
            },
            "InputQty": {
                "required": [
                    "amount",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "The unit of measurement. Example: 'EACH'",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Inventory Count"
                    }
                },
                "description": "Quantity of an item that is input by the seller"
            },
            "AvailToSellQty": {
                "required": [
                    "amount",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "The unit of measurement. Example: 'EACH'",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Inventory Count"
                    }
                },
                "description": "Quantity of an item that is available to be allocated to orders"
            },
            "ReservedQty": {
                "required": [
                    "amount",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "The unit of measurement. Example: 'EACH'",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Inventory Count"
                    }
                },
                "description": "Quantity that has been ordered by the customers but not yet shipped"
            }
        },
        "parameters": {
            "authorization": {
                "name": "Authorization",
                "in": "header",
                "description": "Basic authorization header. Base 64 encodes the Client ID and Client Secret retrieved in step two of the integration steps.",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Basic YzcyOTFjNmItNzI5MC00...."
            },
            "accessToken": {
                "name": "WM_SEC.ACCESS_TOKEN",
                "in": "header",
                "description": "The access token retrieved in the Token API call",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM....."
            },
            "channelType": {
                "name": "WM_CONSUMER.CHANNEL.TYPE",
                "in": "header",
                "description": "A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding",
                "required": false,
                "schema": {
                    "type": "string"
                }
            },
            "correlationId": {
                "name": "WM_QOS.CORRELATION_ID",
                "in": "header",
                "description": "A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "b3261d2d-028a-4ef7-8602-633c23200af6"
            },
            "svcName": {
                "name": "WM_SVC.NAME",
                "in": "header",
                "description": "Walmart Service Name",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Walmart Service Name"
            },
            "accept": {
                "name": "Accept",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            },
            "content-type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            }
        },
        "securitySchemes": {
            "accessToken": {
                "type": "http",
                "scheme": "bearer",
                "description": "Header authentication with a Walmart access token, which is automatically generated using your Client ID and Client Secret. The token is valid for 15 minutes, and will be passed in the WM_SEC.ACCESS_TOKEN header"
            }
        }
    }
}