{
    "openapi": "3.0.1",
    "info": {
        "title": "Inventory Management",
        "description": "Maintaining up-to-date inventory for items on Walmart.com ensures a great customer experience as well as greater sales opportunities. The Inventory Management APIs allow management of current or recently changed inventory supply.",
        "version": "0.7.0"
    },
    "servers": [
        {
            "url": "https:\/\/api-gateway.walmart.com",
            "description": "Production URL"
        }
    ],
    "paths": {
        "\/v3\/inventory": {
            "get": {
                "tags": [
                    "DSV Inventory"
                ],
                "summary": "Inventory",
                "description": "This request retrieves the inventory count for a single item for one specific ship node.",
                "operationId": "getInventoryForAnItem",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "query",
                        "description": "Specifies the stock keeping unit (SKU) item identifier. \n\nThis type of identifier is an arbitrary, alphanumeric identifier that is specified by the drop ship vendor (DSV) and used by the vendor in the specification file to refer to each item. \n\nEither the 'sku' or 'gtin' parameter will be required. The user can only submit one. \n\nThe following special characters in the stock keeping unit (SKU) require encoding: ':', '\/', '?', '#', '[', ']', '@', '!', '$', '&', \"'\", '(', ')', '*', '+', ',', ';', '=', \u2018 \u2019, '{', and '}'. '%' requires encoding if it is part of the stock keeping unit (SKU). Encode spaces with %20. Other characters do not require encoding.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "gtin",
                        "in": "query",
                        "description": "Specifies the global trade item number (GTIN) item identifier. \n\nThe global trade item number is a 14-digit number, including the check digit, that is used worldwide and identifies the Each. If the user's number is less than 14 digits, add zeros at the beginning. \n\nEither the `sku` or `gtin` parameter will be required. The user can only submit one.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "Specifies the distribution facility distributor identifier. \n\n This parameter identifies each facility from which the inventory is requested. The identifier is autogenerated during drop ship vendor (DSV) account creation. Every time users add or update a facility in Supplier Center, a new identifier is generated.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/InventoryResponse",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "1487132332472",
                                    "gtin": "00012947218283",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 23
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "signature": [],
                        "consumerId": [],
                        "accessToken": [],
                        "partner": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "DSV Inventory"
                ],
                "summary": "Update Inventory",
                "description": "This request updates the inventory for an item, with the item global trade item number (GTIN) as the primary item identifier. Use an availability code to identify how inventory quantity is managed for an item.\n\nThe following are valid availability codes:\n\nAC: Use for standard or normal inventory updates.\n\nAA: Use for an item with infinite or unlimited inventory. Quantity is not required when set to AA.\n\nThe drop ship vendor (DSV) supplier sends the `onHand` quantity in the amount field as one whole quantity (unit and value).",
                "operationId": "updateInventoryForAnItem",
                "parameters": [
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "Specifies the distribution facility distributor identifier. \n\n This parameter identifies each facility from which the inventory is requested. The identifier is autogenerated during drop ship vendor (DSV) account creation. Every time users add or update a facility in Supplier Center, a new identifier is generated.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "File fields",
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/Inventory"
                            },
                            "examples": {
                                "SKU": {
                                    "value": {
                                        "sku": "1487132332472",
                                        "availabilityCode": "AC",
                                        "quantity": {
                                            "unit": "EACH",
                                            "amount": "23"
                                        }
                                    }
                                },
                                "GTIN": {
                                    "value": {
                                        "gtin": "00012947218283",
                                        "availabilityCode": "AC",
                                        "quantity": {
                                            "unit": "EACH",
                                            "amount": "23"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/InventoryResponse",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "1487132332472",
                                    "gtin": "00012947218283",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 23
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "signature": [],
                        "consumerId": [],
                        "accessToken": [],
                        "partner": []
                    }
                ]
            }
        },
        "\/v3\/feeds": {
            "post": {
                "tags": [
                    "DSV Inventory"
                ],
                "summary": "Bulk Update Inventory",
                "description": "This request updates inventory for items in bulk. The seller can either use feed type 'DSV_INVENTORY' or 'inventory'.\n\nDSV_INVENTORY: This feed type updates inventory across multiple ship nodes across multiple products. There are two versions: v2.x and v1.5. \n* For v2.x, these updates are global trade item number (GTIN) based and have a flat data structure for enhanced processing. \n* For v1.5, these updates are stock keeping unit (SKU) based and have a complex data structure. \n\nThe multi-node inventory update feed (feedType=DSV_INVENTORY) supports JSON requests and responses only.\n\ninventory: This feed type supports updating inventory across multiple ship nodes across multiple products. There is one version: v1.4.\n* v1.4 supports updating inventory at multiple ship nodes across multiple products.\n\nFor more information about feed types, see the <a href=\"https:\/\/developer.walmart.com\/doc\/us\/us-dsv\/us-dsv-inventory\/\">guide section<\/a>.\n\nRate limits apply to file feeds. Rate limits are 20 calls per hour. The maximum limit of 10,000 items per hour per `shipNode` combinations. The file size limit is 1MB.",
                "operationId": "updateBulkInventory",
                "parameters": [
                    {
                        "name": "feedType",
                        "in": "query",
                        "description": "Specifies the feed type.",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "DSV_INVENTORY",
                                "inventory"
                            ]
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "Specifies the distribution facility distributor identifier. \n\n This parameter identifies each facility from which the inventory is requested. \n\nThe parameter is required for `Inventory` feed type. It is not required for `DSV_INVENTORY` feed type. \n\nThe identifier is autogenerated during drop ship vendor (DSV) account creation. Every time users add or update a facility in Supplier Center, a new identifier is generated.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "File fields",
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/InventoryFeedV2"
                            },
                            "examples": {
                                "1.4": {
                                    "value": {
                                        "InventoryHeader": {
                                            "version": "1.4"
                                        },
                                        "Inventory": [
                                            {
                                                "sku": "CNE498398",
                                                "availabilityCode": "AC",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "amount": "10"
                                                }
                                            },
                                            {
                                                "sku": "ard65005",
                                                "availabilityCode": "AC",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "availableToSell": "5",
                                                    "orderInProgress": "3"
                                                }
                                            }
                                        ]
                                    }
                                },
                                "DSV_MultiNode_Bulk_Inventory_Update_Request": {
                                    "value": {
                                        "inventoryHeader": {
                                            "version": "1.5"
                                        },
                                        "inventory": [
                                            {
                                                "sku": "190086893939",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 100
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "685387364107_SS4_01",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 21
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "5700521553133_toolsnonwfs_2",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 13
                                                        }
                                                    },
                                                    {
                                                        "shipNode": "1000000352",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 12
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "15088243",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 24
                                                        }
                                                    },
                                                    {
                                                        "shipNode": "1000052",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 12
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "AD-01-white-5",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 20
                                                        }
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                },
                                "2.X": {
                                    "value": {
                                        "InventoryFeedHeader": {
                                            "feedType": "DSV_INVENTORY",
                                            "version": "2.0.20220829-15_11_50-api",
                                            "businessUnit": "WALMART_US",
                                            "locale": "en",
                                            "feedDate": "2023-03-13T13:03:33.000Z"
                                        },
                                        "Inventory": [
                                            {
                                                "quantity": 10,
                                                "productId": "01234567891011",
                                                "shipNode": "123456701",
                                                "availabilityCode": "AC"
                                            },
                                            {
                                                "quantity": 11,
                                                "productId": "01234567891011",
                                                "shipNode": "123456702",
                                                "availabilityCode": "AC"
                                            },
                                            {
                                                "quantity": 12,
                                                "productId": "01234567891010",
                                                "shipNode": "123456701",
                                                "availabilityCode": "AC"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/FeedIdInventory",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "feedId": "991B8779687C4D5DBC06DF18DB167192@AQkBAQA"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "signature": [],
                        "consumerId": [],
                        "accessToken": [],
                        "partner": []
                    }
                ]
            }
        },
        "\/v3\/inventories\/{id}": {
            "get": {
                "tags": [
                    "DSV Inventory"
                ],
                "summary": "Single Item Inventory Across Ship Nodes",
                "description": "This request retrieves the inventory count for an item across multiple ship nodes or for one specific ship node. Users can specify the ship node(s) for which they want to fetch the inventory.",
                "operationId": "getMultiNodeInventoryForSkuAndAllShipnodes",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Specifies the value of the stock keeping unit (SKU) or global trade item number (GTIN) item identifier. \n\nThis value is provided by the drop ship vendor (DSV) to identify each item.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "Specifies the distribution facility distributor identifier. \n\n This parameter identifies each facility from which the inventory is requested. The identifier is autogenerated during drop ship vendor (DSV) account creation. Every time users add or update a facility in Supplier Center, a new identifier is generated.",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "productIdType",
                        "in": "query",
                        "description": " Specifies the type of item ID the user is searching. \n\nDefault: sku",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "gtin",
                                "sku"
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/InventoriesDTO",
                                    "x-expose-headers": true
                                },
                                "example": {
                                    "sku": "AR-CTIX-0092",
                                    "gtin": "00012947218283",
                                    "nodes": [
                                        {
                                            "shipNode": "72140715",
                                            "inputQty": {
                                                "unit": "EACH",
                                                "amount": 214
                                            },
                                            "availToSellQty": {
                                                "unit": "EACH",
                                                "amount": 3
                                            },
                                            "reservedQty": {
                                                "unit": "EACH",
                                                "amount": 1
                                            }
                                        },
                                        {
                                            "shipNode": "72140737",
                                            "inputQty": {
                                                "unit": "EACH",
                                                "amount": 21
                                            },
                                            "availToSellQty": {
                                                "unit": "EACH",
                                                "amount": 2
                                            },
                                            "reservedQty": {
                                                "unit": "EACH",
                                                "amount": 0
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "signature": [],
                        "consumerId": [],
                        "accessToken": [],
                        "partner": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "InventoryResponse": {
                "required": [
                    "gtin",
                    "quantity",
                    "sku"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "Indicates the stock keeping unit (SKU) item identifier. \n\nThis is a product identifier provided by the drop ship vendor (DSV) to identify each item."
                    },
                    "gtin": {
                        "type": "string",
                        "description": "Indicates the global trade item number (GTIN) item identifier."
                    },
                    "quantity": {
                        "$ref": "#\/components\/schemas\/SupplyQuantity"
                    }
                },
                "xml": {
                    "name": "Inventory"
                }
            },
            "Quantity": {
                "required": [
                    "amount",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "Indicates the quantity unit of measurement.",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Indicates the quantity of the product available in inventory."
                    }
                },
                "description": "Indicates an object for information about the quantity in inventory."
            },
            "Inventory": {
                "required": [
                    "availabilityCode",
                    "gtin",
                    "quantity"
                ],
                "type": "object",
                "properties": {
                    "gtin": {
                        "type": "string",
                        "description": "Specifies the global trade item number (GTIN) item identifier. \n\nThe global trade item number is a 14-digit number, including the check digit, that is used worldwide and identifies the Each. If the user\u2019s number is less than 14 digits, add zeros at the beginning."
                    },
                    "availabilityCode": {
                        "type": "string",
                        "description": "Specifies how to manage the inventory update. \n\nAC: The code used for standard inventory updates. Assign this code to an item with normal inventory. \n\nAA: An item with infinite inventory. If users set AA as the availability code, they do not need to provide inventory for the item.",
                        "enum": [
                            "AA",
                            "AC"
                        ]
                    },
                    "quantity": {
                        "$ref": "#\/components\/schemas\/Quantity"
                    }
                }
            },
            "SupplyQuantity": {
                "required": [
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "Indicates the unit of measurement the quantity of an item.",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Indicates the value for the quantity of an item."
                    }
                },
                "description": "Indicates an object for the quantity that has been ordered by the customers, but not yet shipped."
            },
            "FeedIdInventory": {
                "type": "object",
                "properties": {
                    "feedId": {
                        "type": "string",
                        "description": "Indicates an identifier, returned from the Bulk Upload API, used for tracking the feed file.\""
                    }
                }
            },
            "InventoryFeedHeader": {
                "required": [
                    "businessUnit",
                    "feedDate",
                    "feedType",
                    "locale",
                    "version"
                ],
                "type": "object",
                "properties": {
                    "version": {
                        "type": "string",
                        "description": "Specifies the inventory feed header version.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    },
                    "feedType": {
                        "type": "string",
                        "description": "Specifies the feed type for inventory feed header information. \n\nFeed types include: \n`DSV_INVENTORY`",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    },
                    "feedDate": {
                        "type": "string",
                        "description": "Specifies the inventory feed header feed date.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    },
                    "locale": {
                        "type": "string",
                        "description": "Specifies the inventory feed header locale.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    },
                    "businessUnit": {
                        "type": "string",
                        "description": "Specifies the inventory feed header business unit.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    }
                },
                "description": "Specifies an object for inventory feed header information.",
                "xml": {
                    "name": "InventoryFeedHeader"
                }
            },
            "InventoryFeedV2": {
                "required": [
                    "inventory",
                    "inventoryFeedHeader"
                ],
                "type": "object",
                "properties": {
                    "inventoryFeedHeader": {
                        "$ref": "#\/components\/schemas\/InventoryFeedHeader"
                    },
                    "inventory": {
                        "type": "array",
                        "description": "Specifies an object for inventory information.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        },
                        "items": {
                            "$ref": "#\/components\/schemas\/InventoryV2"
                        }
                    }
                },
                "xml": {
                    "name": "InventoryFeedV2"
                }
            },
            "InventoryV2": {
                "required": [
                    "availabilityCode",
                    "productId",
                    "shipNode"
                ],
                "type": "object",
                "properties": {
                    "productId": {
                        "type": "string",
                        "description": "Specifies the product identifier for the item. \n\n This parameter can only be a global trade item number (GTIN). \n\nThe global trade item number (GTIN) is a 14-digit number, including the check digit, that is used worldwide and identifies the Each. If the user\u2019s number is less than 14 digits, add zeros at the beginning.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    },
                    "shipNode": {
                        "type": "string",
                        "description": "Specifies the distributor identifier for the distribution facility, used to identify each facility.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    },
                    "availabilityCode": {
                        "type": "string",
                        "description": "Specifies the code that identifies how to manage the inventory update. \n\nCodes include: \n\nAC: The code used for standard inventory updates. Assign this code to an item with normal inventory. \n\nAA: An item with infinite inventory. If users set AA as the `availabilityCode`, they do not need to provide inventory for the item.",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        },
                        "enum": [
                            "AA",
                            "AC"
                        ]
                    },
                    "quantity": {
                        "type": "integer",
                        "description": "Specifies the item quantity available in the inventory.",
                        "format": "int32",
                        "xml": {
                            "namespace": "http:\/\/walmart.com\/"
                        }
                    }
                },
                "description": "Specifies an object for inventory information.",
                "xml": {
                    "name": "Inventory"
                }
            },
            "InventoriesDTO": {
                "required": [
                    "gtin",
                    "sku"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "Indicates the stock keeping unit (SKU) item identifier. \n\n This is a product identifier provided by the drop ship vendor (DSV) to identify each item."
                    },
                    "gtin": {
                        "type": "string",
                        "description": "Indicates the global trade item number (GTIN) item identifier."
                    },
                    "nodes": {
                        "type": "array",
                        "description": "Indicates an array for nodes, to include ship node and allocated quantity.",
                        "items": {
                            "$ref": "#\/components\/schemas\/NodeDTO"
                        }
                    }
                }
            },
            "NodeDTO": {
                "type": "object",
                "properties": {
                    "shipNode": {
                        "type": "string",
                        "description": " Indicates the distribution facility distributor identifier for which the inventory is requested."
                    },
                    "inputQty": {
                        "$ref": "#\/components\/schemas\/InputQty"
                    },
                    "availToSellQty": {
                        "$ref": "#\/components\/schemas\/AvailToSellQty"
                    },
                    "reservedQty": {
                        "$ref": "#\/components\/schemas\/ReservedQty"
                    }
                },
                "description": "Indicates an array for nodes, to include ship node and allocated quantity."
            },
            "InputQty": {
                "required": [
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "Indicates the unit of measurement the quantity of an item.",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Indicates the value for the quantity of an item."
                    }
                },
                "description": "Indicates an object for the on-hand inventory quantity of an item that is provided by the supplier. Input or on-hand inventory is the total inventory, with the amount factoring in both 'availToSellQty' and 'reservedQty'."
            },
            "AvailToSellQty": {
                "required": [
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "Indicates the unit of measurement the quantity of an item.",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Indicates the value for the quantity of an item."
                    }
                },
                "description": "Indicates an object for the quantity of an item that is available to be allocated to orders."
            },
            "ReservedQty": {
                "required": [
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "Indicates the unit of measurement the quantity of an item.",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "Indicates the value for the quantity of an item."
                    }
                },
                "description": "Indicates an object for the quantity that has been ordered by the customers, but not yet shipped."
            }
        },
        "parameters": {
            "authorization": {
                "name": "Authorization",
                "in": "header",
                "description": "Basic authorization header. Base 64 encodes the Client ID and Client Secret retrieved in step two of the integration steps.",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Basic YzcyOTFjNmItNzI5MC00...."
            },
            "accessToken": {
                "name": "WM_SEC.ACCESS_TOKEN",
                "in": "header",
                "description": "The access token retrieved in the Token API call",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM....."
            },
            "channelType": {
                "name": "WM_CONSUMER.CHANNEL.TYPE",
                "in": "header",
                "description": "A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding",
                "required": true,
                "schema": {
                    "type": "string"
                }
            },
            "correlationId": {
                "name": "WM_QOS.CORRELATION_ID",
                "in": "header",
                "description": "A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "b3261d2d-028a-4ef7-8602-633c23200af6"
            },
            "svcName": {
                "name": "WM_SVC.NAME",
                "in": "header",
                "description": "Walmart Service Name",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Walmart Service Name"
            },
            "accept": {
                "name": "Accept",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            },
            "content-type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            }
        },
        "securitySchemes": {
            "accessToken": {
                "type": "http",
                "scheme": "bearer",
                "description": "Header authentication with a Walmart access token, which is automatically generated using your Client ID and Client Secret. The token is valid for 15 minutes, and will be passed in the WM_SEC.ACCESS_TOKEN header"
            },
            "consumerId": {
                "type": "apiKey",
                "in": "header",
                "name": "WM_CONSUMER.ID",
                "description": "Header authentication with your Walmart consumer ID, which is passed in the WM_CONSUMER.ID header. This is always used in tandem with signature authentication (below). When using endpoints that require consumer ID authentication, you must pass the `consumerId` option to the `Configuration` constructor."
            },
            "partner": {
                "type": "apiKey",
                "in": "header",
                "name": "WM_PARTNER.ID",
                "description": "Header authentication with your Walmart partner ID, which is passed in the WM_PARTNER.ID header. Required by Supplier API endpoints. When using endpoints that require partner ID authentication, you must pass the `partnerId` option to the `Configuration` constructor."
            },
            "signature": {
                "type": "apiKey",
                "in": "header",
                "name": "WM_SEC.AUTH_SIGNATURE",
                "description": "Request signature authentication. Request signatures are generated using a combination of request info, a timestamp, and your Walmart consumer ID and private key. The signature is passed in the WM_SEC.AUTH_SIGNATURE header. This is always used in tandem with consumer ID authentication (above). When using endpoints that require signature authentication, you must pass the `privateKey` and `consumerId` options to the `Configuration` constructor."
            }
        }
    }
}